spring.application.name=phone-accessories

spring.datasource.url=jdbc:postgresql://localhost:5432/phone_accessories
spring.datasource.username=postgres
spring.datasource.password=Postgres@123
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8081
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true